#include<stdio.h>
int main()
{
    long long x;
    for (;;)
    {
    if (scanf("%lld",&x) == EOF) break;
    printf("Hailstone generated by %lld:\n",x);
    int i = 0;
    for(;;)
    {
        printf("%lld ",x);
        i++;
        switch(x%2)
        {
        case 1 : x = 3*x+1;
        break;
        default : x = x/2;
        }
        if (x == 1) 
        {
            printf("1");
            i++;
            break;
        }
        
    }
    printf("\nNumber of hailstone generated:%d\n\n",i);
}
}
